// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTAURANT.Data;

namespace RESTAURANT.Migrations
{
    [DbContext(typeof(BD_context))]
    [Migration("20201009144744_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RESTAURANT.Models.Menu", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Cooking_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Name_dish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Volume_Ingredient_1")
                        .HasColumnType("int");

                    b.Property<int>("Volume_Ingredient_2")
                        .HasColumnType("int");

                    b.Property<int>("Volume_Ingredient_3")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ID_dish_1");
                });

            modelBuilder.Entity("RESTAURANT.Models.Order", b =>
                {
                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FGS_employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefon")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("check")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ID_employees");
                });

            modelBuilder.Entity("RESTAURANT.Models.Position", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name_Positions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ID_Positions");
                });

            modelBuilder.Entity("RESTAURANT.Models.Warehouse", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Incept_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MenuID")
                        .HasColumnType("bigint");

                    b.Property<long?>("MenuID1")
                        .HasColumnType("bigint");

                    b.Property<long?>("MenuID2")
                        .HasColumnType("bigint");

                    b.Property<string>("Name_Ingredient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Shelf_life")
                        .HasColumnType("datetime2");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("MenuID1");

                    b.HasIndex("MenuID2");

                    b.ToTable("ID_Ingredient_1");
                });

            modelBuilder.Entity("RESTAURANT.Models.Warehouse", b =>
                {
                    b.HasOne("RESTAURANT.Models.Menu", null)
                        .WithMany("ID_Ingredient_1")
                        .HasForeignKey("MenuID");

                    b.HasOne("RESTAURANT.Models.Menu", null)
                        .WithMany("ID_Ingredient_2")
                        .HasForeignKey("MenuID1");

                    b.HasOne("RESTAURANT.Models.Menu", null)
                        .WithMany("ID_Ingredient_3")
                        .HasForeignKey("MenuID2");
                });
#pragma warning restore 612, 618
        }
    }
}
